UPSTREAM: Add missing build dependency to fwupdplugin-self-test
Parallel builds sometimes fail due to a header not having been generated
yet. Fix by adding fwupdplugin_rs_dep to the deps for fwupdplugin-self-test.

The build error can be reliably reproduced like so:

```
$ meson setup build
$ cd build
$ ninja libfwupdplugin/fwupdplugin-self-test.p/fu-self-test.c.o
[...snip...]
In file included from ../libfwupdplugin/fu-archive-firmware.h:10,
                 from ../libfwupdplugin/fwupdplugin.h:13,
                 from ../libfwupdplugin/fu-self-test.c:11:
../libfwupdplugin/fu-archive.h:12:10: fatal error: fu-archive-struct.h: No such file or directory
   12 | #include "fu-archive-struct.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

(cherry picked from commit c80bff37553c6c782d341a63870566605f4c6a06)

BUG=b:315907448
TEST=cros_workon start sys-apps/fwupd
TEST=FEATURES=test emerge-reven sys-apps/fwupd

Change-Id: I3f6f2c9ab24dea11157ac4d8fce67f6d60ef6828
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/fwupd/+/5136461
Tested-by: Nicholas Bishop <nicholasbishop@google.com>
Reviewed-by: Kyle Williams <kdgwill@chromium.org>
Reviewed-by: Sean Paul <sean@poorly.run>
Commit-Queue: Kyle Williams <kdgwill@chromium.org>
Auto-Submit: Nicholas Bishop <nicholasbishop@google.com>